---
# vi:syntax=yaml
remote_user: "heat-admin"
become: "True"
result_dir: "{{inventory_dir}}/results"
#result_dir: "/home/stack/"

controller_checks:
    #### COMMON ####
    chronyd_ntpd_running:
        url: ""
        detail: "Both chronyd and ntp are not running.  Time may drift"
    chronyd_ntpd_synced:
        url: ""
        detail: "chronyd or ntp are running, but time is not synced"
    #### GLANCE ####
    glance_api_running:
        url: "none"
        detail: "openstack-glance-api is not running"
    glance_registry_running:
        url: "none"
        detail: "openstack-glance-registry is not running"
    glance_db_connection: 
        url: ""
        detail: "Connection to Glance DB Failed.  Check Login credentials in /etc/glance/glance-api.conf"
    glance_db_empty: 
        url: "none"
        detail: "Connection to Glance DB working, but the database has no tables.  Run 'glance-manage db_sync' to populate database"
    glance_rabbit_user_blank:
        url: ""
        detail: "There is no rabbitmq_userid specified in /etc/glance/glance-api.conf"
    glance_rabbit_password_blank:
        url: ""
        detail: "There is no rabbit_password specified in /etc/glance/glance-api.conf"
    glance_rabbit_hosts_blank:
        url: ""
        detail: "Both rabbit_host and rabbit_hosts are blank.  Check /etc/glance/glance-api.conf"
    glance_rabbit_hosts_connection:
        url: ""
        detail: "Glance - Connection to RabbitMQ Failed.  Check RabbitMQ as well as entries for rabbit in /etc/glance/glance-api.conf for rabbit_hosts, rabbit_userid, and rabbit_password"
    glance_rabbit_host_connection:
        url: ""
        detail: "Glance - Connection to RabbitMQ Failed.  Check RabbitMQ as well as entries for rabbit in /etc/glance/glance-api.conf for rabbit_host, rabbit_port, rabbit_userid, and rabbit_password"
    glance_api_keystone_token_get:
        url: ""
        detail: "Glance API authentication to keystone failed.  Check /etc/glance/glance-api.conf and keystone"
    glance_registry_keystone_token_get:
        url: ""
        detail: "Glance Registry authentication to keystone failed.  Check /etc/glance/glance-registry.conf and keystone"
    glance_keystone_endpoint:
        url: ""
        detail: "Glance endpoint not found in Keystone.  This may be due to keystone auth failing or may be the endpoint was never created."
    glance_keystone_endpoint_response:
        url: ""
        detail: "Glance endpoint defined, but it cannot be reached.  Is it responding?  Is there a firewall blocking the port?"
    glance_backend_supported:
        url: ""
        details: "The default store defined in /etc/glance/glance-api.conf is not setup for checking with this script or is invalid."
    #### NOVA CONTROLLER / COMPUTE ####
    nova_api_running:
        url: "none"
        detail: "openstack-nova-api is not running"
    nova_scheduler_running:
        url: "none"
        detail: "openstack-nova-scheduler is not running"
    nova_conductor_running:
        url: "none"
        detail: "openstack-nova-conductor is not running"
    nova_novncproxy_running:
        url: "none"
        detail: "openstack-nova-novncproxy is not running"
    nova_consoleauth_running:
        url: "none"
        detail: "openstack-nova-consoleauth is not running"
    nova_db_connection:
        url: ""
        detail: "Connection to Nova DB Failed.  Check Login credentials in /etc/nova/nova.conf"
    nova_db_empty:
        url: "none"
        detail: "Connection to Nova DB working, but the database has no tables.  Run 'nova-manage db sync' to populate database"
    nova_rabbit_user_blank:
        url: ""
        detail: "There is no rabbitmq_userid specified in /etc/nova/nova.conf"
    nova_rabbit_password_blank:
        url: ""
        detail: "There is no rabbit_password specified in /etc/nova/nova.conf"
    nova_rabbit_hosts_blank:
        url: ""
        detail: "Both rabbit_host and rabbit_hosts are blank.  Check /etc/nova/nova.conf"
    nova_rabbit_hosts_connection:
        url: ""
        detail: "Nova - Connection to RabbitMQ Failed.  Check RabbitMQ as well as entries for rabbit in /etc/nova/nova.conf for rabbit_hosts, rabbit_userid, and rabbit_password"
    nova_rabbit_host_connection:
        url: ""
        detail: "Nova - Connection to RabbitMQ Failed.  Check RabbitMQ as well as entries for rabbit in /etc/nova/nova.conf for rabbit_host, rabbit_port, rabbit_userid, and rabbit_password"
    nova_keystone_token_get:
        url: ""
        detail: "Nova authentication to keystone failed.  Check /etc/nova/nova.conf and keystone"
    nova_keystone_endpoint:
        url: ""
        detail: "Nova endpoint not found in Keystone.  This may be due to keystone auth failing or may be the endpoint was never created."
    nova_keystone_endpoint_response:
        url: ""
        detail: "Nova endpoint defined, but it cannot be reached.  Is it responding?  Is there a firewall blocking the port?"
    #### Neutron ####
    neutron_server_running:
        url: "none"
        detail: "neutron-server is not running"
    neutron_dhcp_agent_running:
        url: "none"
        detail: "neutron-dhcp-agent is not running"
    neutron_l3_agent_running:
        url: "none"
        detail: "neutron-l3-agent is not running"
    neutron_metadata_agent_running:
        url: "none"
        detail: "neutron-metadata-agent is not running"
    neutron_openvswitch_agent_running:
        url: "none"
        detail: "neutron-openvswitch-agent is not running"
    neutron_db_connection: 
        url: ""
        detail: "Connection to neutron DB Failed.  Check Login credentials in /etc/neutron/neutron.conf"
    neutron_db_empty: 
        url: "none"
        detail: "Connection to neutron DB working, but the database has no tables.  Run 'neutron-manage db_sync' to populate database"
    neutron_rabbit_user_blank:
        url: ""
        detail: "There is no rabbitmq_userid specified in /etc/neutron/neutron.conf"
    neutron_rabbit_password_blank:
        url: ""
        detail: "There is no rabbit_password specified in /etc/neutron/neutron.conf"
    neutron_rabbit_hosts_blank:
        url: ""
        detail: "Both rabbit_host and rabbit_hosts are blank.  Check /etc/neutron/neutron.conf"
    neutron_rabbit_hosts_connection:
        url: ""
        detail: "neutron - Connection to RabbitMQ Failed.  Check RabbitMQ as well as entries for rabbit in /etc/neutron/neutron.conf for rabbit_hosts, rabbit_userid, and rabbit_password"
    neutron_rabbit_host_connection:
        url: ""
        detail: "neutron - Connection to RabbitMQ Failed.  Check RabbitMQ as well as entries for rabbit in /etc/neutron/neutron.conf for rabbit_host, rabbit_port, rabbit_userid, and rabbit_password"
    neutron_server_keystone_token_get:
        url: ""
        detail: "neutron API authentication to keystone failed.  Check /etc/neutron/neutron.conf and keystone"
    neutron_keystone_endpoint:
        url: ""
        detail: "neutron endpoint not found in Keystone.  This may be due to keystone auth failing or may be the endpoint was never created."
    neutron_keystone_endpoint_response:
        url: ""
        detail: "neutron endpoint defined, but it cannot be reached.  Is it responding?  Is there a firewall blocking the port?"
